### ISSUE TITLE
Add class names to components

### ISSUE THREAD

**Issue by CodinCat** [trendmicro-frontend/react-paginations#2]
Hi,

Currently most classes are anonymous classes (include other components under @trendmicro-frontend):

```js
export default class extends Component {
                 // ^^ no class name 
```

without given a class name, the component becomes an anonymous component and [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) will just show `_default`

![2017-03-10 5 19 43](https://cloud.githubusercontent.com/assets/3193344/23789456/d3dd9182-05b5-11e7-8ea1-388c60673eab.png)

it's not friendly for debugging.

**Comment by cheton** [comment]
Fixed in v0.5
